name: firebase_excel_export
description: "A Flutter package to export Firestore collections to Excel with customizable headers and data mapping."
version: 0.0.7
homepage: https://github.com/anwarsafy/firebase_excel_export

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.5.1
  excel: ^4.0.6
  universal_html: ^2.2.4
  easy_localization: ^3.0.7
  firebase_core: ^3.8.1
  fake_cloud_firestore: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:


# Add assets here if needed
# assets:
#   - images/example_image.png

# Add fonts here if needed
# fonts:
#   - family: CustomFont
#     fonts:
#       - asset: fonts/CustomFont-Regular.ttf

# Repository and issue tracker URLs for better visibility
repository: https://github.com/anwarsafy/firebase_excel_export
issue_tracker: https://github.com/yourusername/firebase_excel_export/issues
